const accent = "#ff6600";
const accentLight = "#eff6ff";
const slate900 = "#360f5a";
const slate700 = "#334155";
const slate600 = "#475569";
const slate500 = "#64748b";
const slate200 = "#e2e8f0";
const slate50 = "#f8fafc";
const white = "#ffffff";

const episodes = [
  {
    guest: "Chris Walker",
    image: "/Chris Walker.avif",
    title: "Demand Gen Is Broken — And What Actually Replaces It",
    summary:
      "Traditional demand gen models are failing B2B companies. Chris Walker breaks down why MQL-based thinking creates misalignment between marketing activity and revenue outcomes, and what buyer-centric, influence-first marketing looks like when done right.",
    takeaway: "Pipeline isn't generated by leads—it's created through influence and trust.",
    topics: ["Demand Gen", "Pipeline", "Buyer-Centric Marketing", "Revenue Operations"],
    context: "Chris Walker is founder of Refine Labs and one of the most prominent voices in B2B demand generation strategy.",
  },
  {
    guest: "Jay Baer",
    image: "/JayBaer-JustinKeller.avif",
    title: "Speed, Differentiation, and Why Most Marketing Gets Ignored",
    summary:
      "In a world where everyone is doing incremental improvements to the same playbooks, Jay Baer argues that the only path to real marketing impact is genuine differentiation—and that speed of response is itself a competitive advantage few companies are exploiting.",
    takeaway: "Different is better than better.",
    topics: ["Differentiation", "Speed", "GTM Strategy", "Brand"],
    context: "Jay Baer is a Hall of Fame keynote speaker and author of 7 books on marketing and customer experience.",
  },
  {
    guest: "Tim Davidson",
    image: "/TimDavidson.avif",
    title: "What Actually Drives Pipeline in Modern B2B",
    summary:
      "Pipeline isn't the output of a single campaign or channel—it's the result of integrated systems that connect every marketing touchpoint to a revenue outcome. Tim Davidson shares how the best GTM teams are thinking about this and why siloed campaign thinking is holding most companies back.",
    takeaway: "Systems outperform campaigns.",
    topics: ["Pipeline Systems", "GTM", "Integration", "Modern B2B"],
    context: "Tim Davidson is a B2B marketing leader known for revenue-focused marketing strategy and GTM system design.",
  },
];

const themes = [
  {
    theme: "AI in Marketing",
    description: "How AI is reshaping buyer discovery, content production, and GTM execution—and what marketing leaders need to understand to stay ahead.",
    icon: "🤖",
  },
  {
    theme: "ABM & Pipeline Strategy",
    description: "Moving from account-based marketing as a tactic to ABM as an operating system that produces measurable, repeatable pipeline.",
    icon: "🎯",
  },
  {
    theme: "GTM Leadership",
    description: "What separates effective marketing leaders from tacticians—and how the best revenue leaders think about strategy, alignment, and accountability.",
    icon: "🧭",
  },
  {
    theme: "Demand Generation Evolution",
    description: "The shift from lead volume to pipeline quality, and why the metrics that used to matter most are now misleading more companies than they help.",
    icon: "📈",
  },
];

export default function InsightsPage() {
  return (
    <>
      {/* Hero */}
      <section
        style={{
          backgroundColor: slate50,
          borderBottom: `1px solid ${slate200}`,
          padding: "72px 24px 64px",
        }}
      >
        <div className="insights-hero-grid" style={{ maxWidth: "1280px", margin: "0 auto", display: "grid", gridTemplateColumns: "1fr 340px", gap: "48px", alignItems: "center" }}>
          {/* Left: copy */}
          <div>
            <div
              style={{
                fontSize: "12px",
                fontWeight: 700,
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                color: accent,
                marginBottom: "16px",
                display: "flex",
                alignItems: "center",
                gap: "8px",
              }}
            >
              <span style={{ display: "inline-block", width: "20px", height: "2px", backgroundColor: accent, borderRadius: "1px" }} />
              Podcast & Insights
            </div>
            <h1
              style={{
                fontSize: "clamp(32px, 5vw, 52px)",
                fontWeight: 800,
                color: slate900,
                letterSpacing: "-0.03em",
                marginBottom: "20px",
              }}
            >
              Insights on Building Modern Pipeline Engines
            </h1>
            <p
              style={{
                fontSize: "18px",
                color: slate600,
                lineHeight: "1.65",
                marginBottom: "32px",
              }}
            >
              Conversations and perspectives on ABM, GTM strategy, and revenue growth. Not entertainment—strategic thinking with the people actually building the systems that drive B2B pipeline today.
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px" }}>
              <a
                href="https://open.spotify.com/show/1OsJDdLyEmgmhoaMnglBal"
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "10px",
                  backgroundColor: "#1db954",
                  color: white,
                  textDecoration: "none",
                  fontWeight: 700,
                  fontSize: "14px",
                  padding: "12px 22px",
                  borderRadius: "9px",
                }}
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 0C5.4 0 0 5.4 0 12s5.4 12 12 12 12-5.4 12-12S18.66 0 12 0zm5.521 17.34c-.24.359-.66.48-1.021.24-2.82-1.74-6.36-2.101-10.561-1.141-.418.122-.779-.179-.899-.539-.12-.421.18-.78.54-.9 4.56-1.021 8.52-.6 11.64 1.32.42.18.479.659.301 1.02zm1.44-3.3c-.301.42-.841.6-1.262.3-3.239-1.98-8.159-2.58-11.939-1.38-.479.12-1.02-.12-1.14-.6-.12-.48.12-1.021.6-1.141C9.6 9.9 15 10.561 18.72 12.84c.361.181.54.78.241 1.2zm.12-3.36C15.24 8.4 8.82 8.16 5.16 9.301c-.6.179-1.2-.181-1.38-.721-.18-.601.18-1.2.72-1.381 4.26-1.26 11.28-1.02 15.721 1.621.539.3.719 1.02.419 1.56-.299.421-1.02.599-1.559.3z"/>
                </svg>
                Listen on Spotify
              </a>
              <a
                href="https://podcasts.apple.com/us/podcast/making-fun-of-marketing/id1673785229"
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "10px",
                  backgroundColor: "#8b5cf6",
                  color: white,
                  textDecoration: "none",
                  fontWeight: 700,
                  fontSize: "14px",
                  padding: "12px 22px",
                  borderRadius: "9px",
                }}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src="/apple-podcast-logo.png" alt="" aria-hidden="true" style={{ width: "36px", height: "36px", objectFit: "contain" }} />
                Listen on Apple Podcasts
              </a>
            </div>
          </div>

          {/* Right: podcast cover art */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/Making-Fun-of-Marketing-Cover.jpg"
            alt="Making Fun of Marketing with Scott Logan Podcast"
            style={{
              width: "100%",
              height: "auto",
              borderRadius: "16px",
              boxShadow: "0 1px 2px rgba(26,15,54,0.04), 0 4px 8px rgba(26,15,54,0.06), 0 12px 28px rgba(26,15,54,0.08), 0 28px 56px rgba(26,15,54,0.05), 0 48px 96px rgba(26,15,54,0.08), 0 72px 144px rgba(0,0,0,0.10)",
            }}
          />
        </div>
      </section>

      {/* Featured Episodes */}
      <section style={{ backgroundColor: white, padding: "80px 24px", borderBottom: `1px solid ${slate200}` }}>
        <div style={{ maxWidth: "1280px", margin: "0 auto" }}>
          <div style={{ marginBottom: "48px" }}>
            <div
              style={{
                fontSize: "12px",
                fontWeight: 700,
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                color: accent,
                marginBottom: "12px",
                display: "flex",
                alignItems: "center",
                gap: "8px",
              }}
            >
              <span style={{ display: "inline-block", width: "20px", height: "2px", backgroundColor: accent, borderRadius: "1px" }} />
              Featured Episodes
            </div>
            <h2
              style={{
                fontSize: "clamp(24px, 3vw, 34px)",
                fontWeight: 800,
                color: slate900,
                letterSpacing: "-0.03em",
              }}
            >
              Conversations with Revenue Leaders
            </h2>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: "32px" }}>
            {episodes.map((ep, i) => (
              <a
                key={i}
                href="https://open.spotify.com/show/1OsJDdLyEmgmhoaMnglBal"
                target="_blank"
                rel="noopener noreferrer"
                style={{ textDecoration: "none" }}
              >
                <div
                  className="ep-card ep-card-hover"
                  style={{
                    backgroundColor: slate50,
                    borderRadius: "14px",
                    border: `1px solid ${slate200}`,
                    overflow: "hidden",
                    display: "grid",
                    gridTemplateColumns: "300px 1fr",
                  }}
                >
                  {/* Thumbnail */}
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={ep.image}
                    alt={ep.guest}
                    style={{
                      width: "100%",
                      height: "auto",
                      display: "block",
                    }}
                  />

                  {/* Content */}
                  <div style={{ padding: "28px 32px" }}>
                    <div style={{ fontSize: "13px", fontWeight: 700, color: accent, marginBottom: "6px" }}>
                      {ep.guest}
                    </div>
                    <h3
                      style={{
                        fontSize: "19px",
                        fontWeight: 700,
                        color: slate900,
                        letterSpacing: "-0.02em",
                        lineHeight: "1.3",
                        marginBottom: "12px",
                      }}
                    >
                      {ep.title}
                    </h3>
                    <p
                      style={{
                        fontSize: "13px",
                        color: slate500,
                        fontStyle: "italic",
                        marginBottom: "12px",
                        lineHeight: "1.5",
                      }}
                    >
                      {ep.context}
                    </p>
                    <p
                      style={{
                        fontSize: "14px",
                        color: slate600,
                        lineHeight: "1.65",
                        marginBottom: "20px",
                      }}
                    >
                      {ep.summary}
                    </p>

                    <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "center" }}>
                      <div
                        style={{
                          backgroundColor: accentLight,
                          borderRadius: "8px",
                          padding: "10px 14px",
                          flexGrow: 1,
                          minWidth: "200px",
                        }}
                      >
                        <div style={{ fontSize: "10px", fontWeight: 700, color: accent, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: "4px" }}>Key Takeaway</div>
                        <p style={{ fontSize: "13px", fontStyle: "italic", color: accent, fontWeight: 500 }}>&quot;{ep.takeaway}&quot;</p>
                      </div>
                      <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
                        {ep.topics.map((t) => (
                          <span key={t} style={{ fontSize: "11px", fontWeight: 600, backgroundColor: white, color: slate600, border: `1px solid ${slate200}`, padding: "3px 10px", borderRadius: "100px" }}>
                            {t}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* Key Themes */}
      <section style={{ backgroundColor: slate50, padding: "80px 24px", borderBottom: `1px solid ${slate200}` }}>
        <div style={{ maxWidth: "1280px", margin: "0 auto" }}>
          <div style={{ marginBottom: "48px" }}>
            <div
              style={{
                fontSize: "12px",
                fontWeight: 700,
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                color: accent,
                marginBottom: "12px",
                display: "flex",
                alignItems: "center",
                gap: "8px",
              }}
            >
              <span style={{ display: "inline-block", width: "20px", height: "2px", backgroundColor: accent, borderRadius: "1px" }} />
              Recurring Themes
            </div>
            <h2
              style={{
                fontSize: "clamp(24px, 3vw, 34px)",
                fontWeight: 800,
                color: slate900,
                letterSpacing: "-0.03em",
              }}
            >
              What the Best Revenue Leaders are Thinking About
            </h2>
          </div>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
              gap: "20px",
            }}
          >
            {themes.map((t) => (
              <div
                key={t.theme}
                className="float"
                style={{
                  backgroundColor: white,
                  borderRadius: "12px",
                  padding: "28px",
                  border: `1px solid ${slate200}`,
                }}
              >
                <div style={{ fontSize: "28px", marginBottom: "14px" }}>{t.icon}</div>
                <h3 style={{ fontSize: "17px", fontWeight: 700, color: slate900, letterSpacing: "-0.02em", marginBottom: "10px" }}>
                  {t.theme}
                </h3>
                <p style={{ fontSize: "14px", color: slate600, lineHeight: "1.65" }}>
                  {t.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What I've Learned */}
      <section style={{ backgroundColor: slate900, padding: "80px 24px" }}>
        <div style={{ maxWidth: "840px", margin: "0 auto" }}>
          <div
            style={{
              fontSize: "12px",
              fontWeight: 700,
              letterSpacing: "0.1em",
              textTransform: "uppercase",
              color: accent,
              marginBottom: "16px",
              display: "flex",
              alignItems: "center",
              gap: "8px",
            }}
          >
            <span style={{ display: "inline-block", width: "20px", height: "2px", backgroundColor: accent, borderRadius: "1px" }} />
            Key Takeaways
          </div>
          <h2
            style={{
              fontSize: "clamp(24px, 4vw, 36px)",
              fontWeight: 800,
              color: white,
              letterSpacing: "-0.03em",
              marginBottom: "16px",
            }}
          >
            What I&apos;ve Learned from Revenue Leaders
          </h2>
          <p style={{ fontSize: "16px", color: "#94a3b8", lineHeight: "1.7", marginBottom: "40px" }}>
            After years of hosting these conversations, certain principles keep surfacing across every guest, every company, every market. Here&apos;s what the consensus of the best minds in B2B revenue has taught me.
          </p>

          <div style={{ display: "flex", flexDirection: "column" }}>
            {[
              { insight: "MQLs are losing relevance", detail: "Pipeline ownership matters more than lead volume. Measure what creates revenue, not what's easy to count." },
              { insight: "Speed is a competitive advantage", detail: "Teams that execute faster consistently outperform those that plan longer. Responsiveness compounds." },
              { insight: "Content drives demand, not just traffic", detail: "Influence happens before conversion. The buyer journey starts long before they raise their hand." },
              { insight: "Sales and marketing alignment is non-negotiable", detail: "Misaligned teams create pipeline leakage at every stage. Alignment creates multiplied output with the same headcount." },
              { insight: "AI is reshaping discovery", detail: "Buyers are finding vendors through LLMs and AI search engines. Optimize for that reality, not just traditional Google." },
              { insight: "Systems outperform campaigns", detail: "One-off efforts create spikes. Integrated systems create compounding pipeline growth that doesn't require constant reinvention." },
            ].map((item, i, arr) => (
              <div
                key={i}
                style={{
                  display: "flex",
                  gap: "20px",
                  padding: "22px 0",
                  borderBottom: i < arr.length - 1 ? "1px solid #4d1a7a" : "none",
                }}
              >
                <div
                  style={{
                    fontSize: "20px",
                    fontWeight: 800,
                    color: accent,
                    letterSpacing: "-0.02em",
                    minWidth: "32px",
                    marginTop: "2px",
                  }}
                >
                  {String(i + 1).padStart(2, "0")}
                </div>
                <div>
                  <div style={{ fontSize: "17px", fontWeight: 700, color: white, marginBottom: "6px", letterSpacing: "-0.01em" }}>
                    {item.insight}
                  </div>
                  <div style={{ fontSize: "14px", color: "#94a3b8", lineHeight: "1.6" }}>{item.detail}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <style>{`
        @media (max-width: 700px) {
          .ep-card { grid-template-columns: 1fr !important; }
          .ep-card > div:first-child { min-height: 120px; }
        }
      `}</style>
    </>
  );
}
